# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-1809
USER ContainerAdministrator

ENV PATH="$PATH;C:\git\cmd" `
    GIT_VERSION="2.23.0.1"

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN $major, $minor, $patch, $build = $env:GIT_VERSION.split('.'); `
    if ($build -ne '1') { `
        $exePath = ('MinGit-{0}.{1}.{2}.{3}-busybox-64-bit.zip' -f $major, $minor, $patch, $build); `
    } `
    else { `
        $exePath = ('MinGit-{0}.{1}.{2}-busybox-64-bit.zip' -f $major, $minor, $patch); `
    } `
    $url = ('https://github.com/git-for-windows/git/releases/download/v{0}.{1}.{2}.windows.{3}/{4}' -f $major, $minor, $patch, $build, $exePath); `
    Invoke-WebRequest -UseBasicParsing $url -OutFile git.zip; `
    Expand-Archive git.zip -DestinationPath C:\git; `
    Remove-Item git.zip; `
    git --version;

ADD windows/* /bin/

CMD [ "pwsh", "C:\\bin\\clone.ps1" ]
