# escape=`

FROM mcr.microsoft.com/powershell:nanoserver-ltsc2022

RUN `
  mkdir tmp && mkdir git`
	&& curl -sSfLo tmp/file.zip https://github.com/git-for-windows/git/releases/download/v2.33.0.windows.2/MinGit-2.33.0.2-64-bit.zip `
  && tar -C c:\git -oxzf tmp/file.zip`
  && rmdir /Q /S tmp

ADD windows/* /bin/

# https://github.com/PowerShell/PowerShell/issues/6211#issuecomment-367477137
USER ContainerAdministrator

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
CMD [ "pwsh", "C:\\bin\\clone.ps1" ]
